FROM maven:3.6.3-jdk-11 as builder

ARG PORT
ARG MYSQL_PORT
ARG MYSQL_HOST
ARG MYSQL_USERNAME
ARG MYSQL_PASSWORD
ARG MYSQL_DATABASE
ARG SECRET_KEY

ENV PORT $PORT
ENV MYSQL_PORT $MYSQL_PORT
ENV MYSQL_HOST $MYSQL_HOST
ENV MYSQL_USERNAME $MYSQL_USERNAME
ENV MYSQL_PASSWORD $MYSQL_PASSWORD
ENV MYSQL_DATABASE $MYSQL_DATABASE
ENV SECRET_KEY $SECRET_KEY

WORKDIR /app

COPY . .

RUN mvn clean install

FROM openjdk:11.0.6-slim

ENV PORT 80
ENV MYSQL_PORT 3306
ENV MYSQL_HOST localhost
ENV MYSQL_USERNAME user
ENV MYSQL_PASSWORD password
ENV MYSQL_DATABASE stats19
ENV SECRET_KEY secret_key

WORKDIR /app

COPY --from=builder /app/target/api-0.0.1-SNAPSHOT.jar /app/api.jar

EXPOSE ${PORT}

CMD ["java", "-jar", "api.jar"]